spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      # TODO: rename these to bocean
      jdbc-url: >
        jdbc:postgresql://localhost:5432/trickle
      pool-name: bocean-pool
      username: trickle
      password: trickle
