spring:
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  profiles:
    active: local
    mvc:
      static-path-pattern: "/static/**"
logging:
  level:
    root: "warn"
    org.springframework.web: "debug"
    in.stonecolddev.bocean: "debug"