spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/trickle
    username: trickle
    password: trickle
    mvc:
      static-path-pattern=/static/**:
logging:
  level:
    root: "warn"
    org.springframework.web: "debug"
    in.stonecolddev.trickle: "debug"
